version: '3.3'

services:
  process-monitor:
    build: .
    container_name: process-monitor
    pid: "host"
    volumes:
      - /proc:/proc
    extra_hosts:
      - "host.docker.internal:10.0.0.210"
    command: python ./monitor_processes.py
    restart: always
